sudo: false
language: python

matrix:
    include:
      - python: 3.4
        env: TOX_ENV=py34 NOSE_VERSION=1.0.0 PYTEST_VERSION=3.0.5
      - python: 3.4
        env: TOX_ENV=py34
      - python: 3.5
        env: TOX_ENV=py35
      - python: 3.6
        env: TOX_ENV=py36
      - python: 3.7
        env: TOX_ENV=py37
        dist: xenial
      - python: 3.6
        env: TOX_ENV=flake8

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOX_ENV

after_script:
  - coveralls
